on:
  push:
    tags:
      - "v*" # Version tags like v1.2.3
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release_build:
  release_create:
    requires:
      - release_build
  docker_image:
    requires:
      - release_create
