/// Woodpecker CI Provider Plugin for CIGen
use anyhow::{Context, Result};
use cigen::plugin::protocol::{diagnostic, plugin_server::Plugin, *};
use serde_yaml::{Mapping, Value};
use std::collections::{BTreeMap, HashMap};
use tonic::{Request, Response, Status};

/// Plugin version and metadata
const PLUGIN_NAME: &str = "provider/woodpecker";
const PLUGIN_VERSION: &str = "0.1.0";
const PROTOCOL_VERSION: u32 = 1;

/// Woodpecker CI provider plugin
#[derive(Debug, Default)]
pub struct WoodpeckerProvider {}

#[tonic::async_trait]
impl Plugin for WoodpeckerProvider {
    async fn handshake(&self, request: Request<Hello>) -> Result<Response<PluginInfo>, Status> {
        let hello = request.into_inner();

        // Verify protocol compatibility
        if hello.core_protocol != PROTOCOL_VERSION {
            return Err(Status::failed_precondition(format!(
                "Protocol version mismatch: core={}, plugin={}",
                hello.core_protocol, PROTOCOL_VERSION
            )));
        }

        tracing::info!(
            "Handshake from core version {} (protocol {})",
            hello.core_version,
            hello.core_protocol
        );

        let info = PluginInfo {
            name: PLUGIN_NAME.to_string(),
            version: PLUGIN_VERSION.to_string(),
            protocol: PROTOCOL_VERSION,
            capabilities: vec![
                "provider:woodpecker".to_string(),
                "cache:native".to_string(),
                "matrix:build".to_string(),
            ],
            requires: vec![],
            conflicts_with: vec!["provider:*".to_string()],
            metadata: std::collections::HashMap::new(),
        };

        Ok(Response::new(info))
    }

    async fn detect(
        &self,
        request: Request<DetectRequest>,
    ) -> Result<Response<DetectResult>, Status> {
        let _req = request.into_inner();

        // Check for .woodpecker/ directory or .woodpecker.yaml file
        let result = DetectResult {
            signals: vec![],
            facts: std::collections::HashMap::new(),
            confidence: 0.0,
            diagnostics: vec![],
        };

        Ok(Response::new(result))
    }

    async fn plan(&self, request: Request<PlanRequest>) -> Result<Response<PlanResult>, Status> {
        let _req = request.into_inner();

        let result = PlanResult {
            resources: vec![],
            deps: vec![],
            diagnostics: vec![],
        };

        Ok(Response::new(result))
    }

    async fn generate(
        &self,
        request: Request<GenerateRequest>,
    ) -> Result<Response<GenerateResult>, Status> {
        let req = request.into_inner();

        tracing::info!("Generating Woodpecker CI config for target: {}", req.target);

        let fragment = Fragment {
            path: ".woodpecker/ci.yaml".to_string(),
            content: "# Generated by cigen-provider-woodpecker\nsteps:\n  - name: test\n    image: alpine\n    commands:\n      - echo 'Hello from Woodpecker'\n".to_string(),
            strategy: MergeStrategy::Replace as i32,
            order: 0,
            format: "yaml".to_string(),
        };

        let result = GenerateResult {
            fragments: vec![fragment],
            diagnostics: vec![],
        };

        Ok(Response::new(result))
    }

    async fn validate(
        &self,
        request: Request<ValidateRequest>,
    ) -> Result<Response<ValidateResult>, Status> {
        let _req = request.into_inner();

        let result = ValidateResult {
            diagnostics: vec![],
        };

        Ok(Response::new(result))
    }

    async fn preflight(
        &self,
        request: Request<PreflightRequest>,
    ) -> Result<Response<PreflightResult>, Status> {
        let _req = request.into_inner();

        tracing::warn!(
            "Preflight check bypassed - job skipping not implemented, all jobs will run"
        );

        let result = PreflightResult {
            should_run: true,
            reason: "preflight_not_implemented".to_string(),
            new_signature: vec![],
        };

        Ok(Response::new(result))
    }
}

fn main() -> Result<()> {
    // Initialize logging to stderr (stdout is used for protobuf messages)
    tracing_subscriber::fmt()
        .with_writer(std::io::stderr)
        .with_env_filter(
            tracing_subscriber::EnvFilter::from_default_env()
                .add_directive("cigen_provider_woodpecker=info".parse()?),
        )
        .with_target(false)
        .without_time()
        .init();

    tracing::info!("Starting {} v{}", PLUGIN_NAME, PLUGIN_VERSION);

    use cigen::plugin::framing::{receive_message, send_message};
    use std::io::{stdin, stdout};

    // Read Hello message from stdin
    let hello: Hello = receive_message(&mut stdin().lock())?;

    tracing::info!(
        "Received handshake from core version {} (protocol {})",
        hello.core_version,
        hello.core_protocol
    );

    // Verify protocol compatibility
    if hello.core_protocol != PROTOCOL_VERSION {
        anyhow::bail!(
            "Protocol version mismatch: core={}, plugin={}",
            hello.core_protocol,
            PROTOCOL_VERSION
        );
    }

    // Send PluginInfo response
    let info = PluginInfo {
        name: PLUGIN_NAME.to_string(),
        version: PLUGIN_VERSION.to_string(),
        protocol: PROTOCOL_VERSION,
        capabilities: vec![
            "provider:woodpecker".to_string(),
            "cache:native".to_string(),
            "matrix:build".to_string(),
        ],
        requires: vec![],
        conflicts_with: vec!["provider:*".to_string()],
        metadata: std::collections::HashMap::new(),
    };

    send_message(&info, &mut stdout().lock())?;

    tracing::info!("Handshake successful, plugin info sent");

    // Message loop: handle Plan and Generate requests
    tracing::info!("Entering message loop...");

    let mut stdin = stdin().lock();
    let mut stdout = stdout().lock();

    loop {
        match receive_message::<PlanRequest, _>(&mut stdin) {
            Ok(_plan_req) => {
                tracing::info!("Received PlanRequest");

                let plan_result = PlanResult {
                    resources: vec![],
                    deps: vec![],
                    diagnostics: vec![],
                };

                send_message(&plan_result, &mut stdout)?;
                tracing::info!("Sent PlanResult");
            }
            Err(_) => {
                break;
            }
        }

        match receive_message::<GenerateRequest, _>(&mut stdin) {
            Ok(gen_req) => {
                tracing::info!("Received GenerateRequest for target: {}", gen_req.target);

                let gen_result = build_generate_result(&gen_req);

                tracing::info!(
                    "Sending GenerateResult with {} fragment(s)",
                    gen_result.fragments.len()
                );
                send_message(&gen_result, &mut stdout)?;
            }
            Err(_) => {
                break;
            }
        }
    }

    tracing::debug!("Plugin loop terminated");
    Ok(())
}

fn build_generate_result(req: &GenerateRequest) -> GenerateResult {
    let schema = match &req.schema {
        Some(schema) => schema,
        None => {
            return GenerateResult {
                fragments: vec![],
                diagnostics: vec![make_diagnostic(
                    "unknown",
                    anyhow::anyhow!("GenerateRequest missing schema"),
                )],
            };
        }
    };
    let (fragments, diagnostics) = build_workflow_fragments(schema);
    GenerateResult {
        fragments,
        diagnostics,
    }
}

fn build_workflow_fragments(schema: &CigenSchema) -> (Vec<Fragment>, Vec<Diagnostic>) {
    let mut diagnostics = Vec::new();

    let workflow_metadata = parse_workflow_metadata(schema, &mut diagnostics);
    let mut jobs_by_workflow: BTreeMap<String, Vec<JobDefinition>> = BTreeMap::new();
    for job in &schema.jobs {
        let workflow = if job.workflow.is_empty() {
            "ci"
        } else {
            &job.workflow
        };
        jobs_by_workflow
            .entry(workflow.to_string())
            .or_default()
            .push(job.clone());
    }

    let mut fragments = Vec::new();

    for (workflow_name, mut jobs) in jobs_by_workflow {
        jobs.sort_by(|a, b| a.id.cmp(&b.id));
        let metadata = workflow_metadata.get(&workflow_name);
        match render_workflow_file(&workflow_name, &jobs, metadata) {
            Ok(content) => fragments.push(Fragment {
                path: format!(".woodpecker/{workflow_name}.yaml"),
                content,
                strategy: MergeStrategy::Replace as i32,
                order: 0,
                format: "yaml".to_string(),
            }),
            Err(error) => diagnostics.push(make_diagnostic(&workflow_name, error)),
        }
    }

    (fragments, diagnostics)
}

fn parse_workflow_metadata(
    schema: &CigenSchema,
    diagnostics: &mut Vec<Diagnostic>,
) -> HashMap<String, Mapping> {
    let mut result = HashMap::new();
    for workflow in &schema.workflows {
        match serde_yaml::from_str::<Value>(&workflow.yaml) {
            Ok(Value::Mapping(mapping)) => {
                result.insert(workflow.id.clone(), mapping);
            }
            Ok(other) => diagnostics.push(make_diagnostic(
                &workflow.id,
                anyhow::anyhow!(
                    "Expected mapping for workflow metadata but found {:?}",
                    other
                ),
            )),
            Err(err) => diagnostics.push(make_diagnostic(
                &workflow.id,
                anyhow::anyhow!("Failed to parse workflow metadata: {err}"),
            )),
        }
    }
    result
}

fn render_workflow_file(
    _workflow_name: &str,
    jobs: &[JobDefinition],
    metadata: Option<&Mapping>,
) -> anyhow::Result<String> {
    let mut workflow_map = metadata.cloned().unwrap_or_else(Mapping::new);

    // Remove steps key if present (we'll rebuild it)
    let steps_key = Value::String("steps".into());
    workflow_map.remove(&steps_key);

    // Build all steps for all jobs
    let steps = build_steps_sequence(jobs)?;
    workflow_map.insert(steps_key, Value::Sequence(steps));

    let mut yaml = String::from("# DO NOT EDIT - This file is generated by cigen\n");
    yaml.push_str("# Source: .cigen/workflows/\n");
    yaml.push_str("# Regenerate with: cargo run -- --config .cigen generate\n");
    yaml.push_str("#\n");

    let rendered =
        serde_yaml::to_string(&workflow_map).context("Failed to serialize Woodpecker workflow")?;
    yaml.push_str(&rendered);
    Ok(yaml)
}

fn build_steps_sequence(jobs: &[JobDefinition]) -> anyhow::Result<Vec<Value>> {
    let mut steps = Vec::new();

    for job in jobs {
        for step in &job.steps {
            if let Some(step_type) = &step.step_type {
                match step_type {
                    step::StepType::Run(run) => {
                        steps.push(Value::Mapping(convert_run_step(&job.image, run)));
                    }
                    step::StepType::Uses(_) => {
                        // Woodpecker uses plugins differently - would need special handling
                        continue;
                    }
                    step::StepType::RestoreCache(_) | step::StepType::SaveCache(_) => {
                        // Cache handling in Woodpecker is different
                        continue;
                    }
                    step::StepType::Custom(_) => continue,
                }
            }
        }
    }

    Ok(steps)
}

fn convert_run_step(default_image: &str, run: &RunStep) -> Mapping {
    let mut mapping = Mapping::new();

    if !run.name.is_empty() {
        mapping.insert(
            Value::String("name".into()),
            Value::String(run.name.clone()),
        );
    }

    // Use job's default image
    mapping.insert(
        Value::String("image".into()),
        Value::String(default_image.to_string()),
    );

    // Convert single command to commands array
    mapping.insert(
        Value::String("commands".into()),
        Value::Sequence(vec![Value::String(run.command.clone())]),
    );

    if !run.env.is_empty() {
        mapping.insert(
            Value::String("environment".into()),
            map_from_string_map(&run.env),
        );
    }

    // Convert GitHub Actions 'if' to Woodpecker 'when'
    if !run.r#if.is_empty() {
        let mut when_map = Mapping::new();
        // This is a simplified conversion - would need more logic for complex conditions
        when_map.insert(
            Value::String("evaluate".into()),
            Value::String(run.r#if.clone()),
        );
        mapping.insert(Value::String("when".into()), Value::Mapping(when_map));
    }

    mapping
}

fn map_from_string_map(map: &HashMap<String, String>) -> Value {
    let mut mapping = Mapping::new();
    for (key, value) in map {
        mapping.insert(Value::String(key.clone()), Value::String(value.clone()));
    }
    Value::Mapping(mapping)
}

fn make_diagnostic(workflow: &str, error: anyhow::Error) -> Diagnostic {
    Diagnostic {
        level: diagnostic::Level::Error as i32,
        code: "WOODPECKER_GENERATE_ERROR".to_string(),
        title: format!("Failed to generate workflow '{workflow}'"),
        message: error.to_string(),
        fix_hint: String::new(),
        loc: None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn job_with_run_step(id: &str, image: &str, command: &str) -> JobDefinition {
        JobDefinition {
            id: id.to_string(),
            workflow: "ci".to_string(),
            image: image.to_string(),
            steps: vec![Step {
                step_type: Some(step::StepType::Run(RunStep {
                    name: "test step".to_string(),
                    command: command.to_string(),
                    ..Default::default()
                })),
            }],
            ..Default::default()
        }
    }

    #[test]
    fn test_convert_run_step_basic() {
        let run = RunStep {
            name: "Build".to_string(),
            command: "cargo build".to_string(),
            ..Default::default()
        };

        let result = convert_run_step("rust:latest", &run);

        assert_eq!(
            result.get(&Value::String("name".into())),
            Some(&Value::String("Build".into()))
        );
        assert_eq!(
            result.get(&Value::String("image".into())),
            Some(&Value::String("rust:latest".into()))
        );

        let commands = result
            .get(&Value::String("commands".into()))
            .and_then(Value::as_sequence);
        assert!(commands.is_some());
        assert_eq!(
            commands.unwrap(),
            &vec![Value::String("cargo build".into())]
        );
    }

    #[test]
    fn test_convert_run_step_with_env() {
        let mut env = HashMap::new();
        env.insert("FOO".to_string(), "bar".to_string());

        let run = RunStep {
            name: "Test".to_string(),
            command: "cargo test".to_string(),
            env,
            ..Default::default()
        };

        let result = convert_run_step("rust:latest", &run);

        let environment = result
            .get(&Value::String("environment".into()))
            .and_then(Value::as_mapping);
        assert!(environment.is_some());
        assert_eq!(
            environment
                .unwrap()
                .get(&Value::String("FOO".into()))
                .and_then(Value::as_str),
            Some("bar")
        );
    }

    #[test]
    fn test_build_steps_sequence() {
        let jobs = vec![
            job_with_run_step("test", "rust:latest", "cargo test"),
            job_with_run_step("lint", "rust:latest", "cargo clippy"),
        ];

        let steps = build_steps_sequence(&jobs).unwrap();

        assert_eq!(steps.len(), 2);

        // Check first step
        let step1 = steps[0].as_mapping().unwrap();
        assert_eq!(
            step1.get(&Value::String("image".into())),
            Some(&Value::String("rust:latest".into()))
        );
        let commands1 = step1
            .get(&Value::String("commands".into()))
            .and_then(Value::as_sequence)
            .unwrap();
        assert_eq!(commands1, &vec![Value::String("cargo test".into())]);

        // Check second step
        let step2 = steps[1].as_mapping().unwrap();
        let commands2 = step2
            .get(&Value::String("commands".into()))
            .and_then(Value::as_sequence)
            .unwrap();
        assert_eq!(commands2, &vec![Value::String("cargo clippy".into())]);
    }

    #[test]
    fn test_render_workflow_file() {
        let jobs = vec![job_with_run_step("test", "alpine", "echo hello")];

        let result = render_workflow_file("ci", &jobs, None).unwrap();

        // Should contain header comments
        assert!(result.contains("DO NOT EDIT"));
        assert!(result.contains("generated by cigen"));

        // Should contain the step
        assert!(result.contains("alpine"));
        assert!(result.contains("echo hello"));
    }

    #[test]
    fn test_build_workflow_fragments() {
        let schema = CigenSchema {
            jobs: vec![
                job_with_run_step("test", "rust:latest", "cargo test"),
                job_with_run_step("build", "rust:latest", "cargo build"),
            ],
            workflows: vec![],
            ..Default::default()
        };

        let (fragments, diagnostics) = build_workflow_fragments(&schema);

        assert_eq!(diagnostics.len(), 0);
        assert_eq!(fragments.len(), 1); // One workflow file
        assert_eq!(fragments[0].path, ".woodpecker/ci.yaml");
        assert!(fragments[0].content.contains("cargo test"));
        assert!(fragments[0].content.contains("cargo build"));
    }

    #[test]
    fn test_multiple_workflows() {
        let mut job1 = job_with_run_step("test", "rust:latest", "cargo test");
        job1.workflow = "ci".to_string();

        let mut job2 = job_with_run_step("deploy", "alpine", "deploy.sh");
        job2.workflow = "deploy".to_string();

        let schema = CigenSchema {
            jobs: vec![job1, job2],
            workflows: vec![],
            ..Default::default()
        };

        let (fragments, diagnostics) = build_workflow_fragments(&schema);

        assert_eq!(diagnostics.len(), 0);
        assert_eq!(fragments.len(), 2); // Two workflow files

        let paths: Vec<_> = fragments.iter().map(|f| f.path.as_str()).collect();
        assert!(paths.contains(&".woodpecker/ci.yaml"));
        assert!(paths.contains(&".woodpecker/deploy.yaml"));
    }
}
