image: ci_app_base
architectures: ["amd64"]
resource_class: medium

steps:
  - name: Generate Dynamic Config With CIGen
    run: |
      cigen generate \
        --config .cigen/config.yml \
        --workflow test \
        --output .circleci/dynamic_config.yml

  - continue_circleci_pipeline:
      config_path: .circleci/dynamic_config.yml

  # - run:
  #     name: Continue Pipeline
  #     environment:
  #       CONFIG_PATH: .circleci/workflow_config.yml
  #     command: |
  #       # Continue with pipeline
  #       if [ -z "${CIRCLE_CONTINUATION_KEY}" ]; then
  #           echo "CIRCLE_CONTINUATION_KEY is required. Make sure setup workflows are enabled."
  #           exit 1
  #       fi

  #       if [ -z "${CONFIG_PATH}" ]; then
  #           echo "CONFIG_PATH is required."
  #           exit 1
  #       fi

  #       # Using --rawfile to read config from file
  #       jq -n \
  #         --arg continuation "$CIRCLE_CONTINUATION_KEY" \
  #         --rawfile config "$CONFIG_PATH" \
  #         '{"continuation-key": $continuation, "configuration": $config}' \
  #         > /tmp/continuation.json

  #       echo "Next CircleCI config:"
  #       cat /tmp/continuation.json

  #       [[ $(curl \
  #               -o /dev/stderr \
  #               -w '%{http_code}' \
  #               -XPOST \
  #               -H "Content-Type: application/json" \
  #               -H "Accept: application/json"  \
  #               --data "@/tmp/continuation.json" \
  #               "https://circleci.com/api/v2/pipeline/continue") \
  #         -eq 200 ]]
