# File groups for cache keys (artifacts and job status)
source_file_groups:
  bundler:
    - Gemfile
    - Gemfile.lock
    - .ruby-version
  npm:
    - package-lock.json
    - package.json
    - .nvmrc
  rails:
    - app/
    - config/
    - db/
    - lib/
    - public/
    - Rakefile
    - .ruby-version
    - Gemfile
  rspec:
    - (rails)
    - spec/
  ruby:
    - "**/*.rb"
    - "Gemfile*"
    - ".ruby-version"
  javascript:
    - "**/*.js"
    - "**/*.jsx"
    - "**/*.ts"
    - "**/*.tsx"
    - "package*.json"
  rails_assets:
    - "app/assets/**/*"
    - "app/javascript/**/*"
    - "config/webpack/**/*"
