docker:
  default_auth: docker_hub
  auth:
    docker_hub:
      username: $DOCKERHUB_USERNAME
      password: $DOCKERHUB_TOKEN

services:
  postgres:
    image: cimg/postgres:{{ postgres_version }}
    environment:
      POSTGRES_USER: docspring
      POSTGRES_DB: docspring_test

  redis:
    image: cimg/redis:{{ redis_version }}

  minio:
    image: minio/minio:{{ minio_version }}
    environment:
      - MINIO_ROOT_USER=docspring-minio
      - MINIO_ROOT_PASSWORD=minio123123
    entrypoint: bash
    command: |
      -c 'mkdir -p /minio/docspring-test /minio/docspring-dev \
      && minio server /minio --console-address :9001'
