# CI provider to target
provider: circleci
output_path: ./build

# Cache backend configuration
caches:
  # File cache for artifacts (gems, npm packages, etc.)
  artifacts:
    backend: circleci

  # Job status cache for skipping unchanged jobs
  job_status:
    backend: redis
    config:
      url: ${CI_CACHE_REDIS_URL}

# Architecture matrix for multi-arch support
architectures:
  - amd64
  - arm64

# Resource class mapping
resource_classes:
  amd64:
    large: large
    xlarge: xlarge
    medium: medium
    self_hosted: docspring/ci-runner
  arm64:
    large: arm.large
    medium: arm.medium
